#Prueba Pipeline Scan
trigger:
  - master
  - integracion
  - featureX
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: Maven@3
    displayName: Build with Maven
    inputs:
      mavenPomFile: "verademo-main/app/pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.8"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "package"
  - task: Bash@3
    displayName: Veracode Pipeline Scan
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/featureX'))
    inputs:
      targetType: "inline"
      script: |
        curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f /home/vsts/work/1/s/verademo-main/app/target/verademo.war || true
      # VERACODE_API_ID and VERACODE_API_KEY environment variables must reference your API credentials.
      # "|| true" specifies to continue build if Pipeline Scan discovers flaws.
      # To fail the build for new flaws not listed in a baseline file, add an existing baseline file with "-bf <baseline filename>" and remove "|| true".
  - task: Veracode@3
    inputs:
      ConnectionDetailsSelection: 'Credentials'
      apiId: '$(VERACODE_API_ID)'
      apiKey: '$(VERACODE_API_KEY)'
      veracodeAppProfile: 'verademo_azure_apa'
      version: '$(build.buildNumber)'
      filepath: '/home/vsts/work/1/s/verademo-main/app/target/verademo.war'
      sandboxName: 'devSandbox_Azure'
      failBuildIfUploadAndScanBuildStepFails: true
      failBuildOnPolicyFail: true
      maximumWaitTime: '360'
  - task: Bash@3
    displayName: Veracode Policy Scan
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    inputs:
      ConnectionDetailsSelection: 'Credentials'
      apiID: '$(VERACODE_API_ID)'
      apiKey: '$(VERACODE_API_KEY)'
      veracodeAppProfile: 'verademo_azure_apa'
      version: '$(build.buildNumber)'
      filepath: '/home/vsts/work/1/s/verademo-main/app/target/verademo.war'
      failBuildOnPolicyFail: true
      maximumWaitTime: '360'
  - publish: 'verademo-main/results.json' # Save the scan results as a file named results.json.
    artifact: VeracodeBaseline
